#!/usr/bin/env python3
"""Fetch a snapshot of the ALCF user documentation into docs/.

The ALCF user guides are an MkDocs site (github.com/argonne-lcf/user-guides).
Rather than scrape rendered HTML, we pull the raw Markdown sources for a curated
set of high-value pages so the agent gets clean, chunk-friendly text. Add pages
to PAGES as the agent's scope grows.

Run by .github/workflows/refresh-docs.yml nightly. Idempotent: overwrites files;
the workflow commits only if something changed.
"""
from __future__ import annotations

import pathlib
import sys
import requests

RAW = "https://raw.githubusercontent.com/argonne-lcf/user-guides/main/docs"

# (source path under docs/, local filename)
PAGES = [
    ("services/inference-endpoints.md", "inference-endpoints.md"),
    ("services/iri-api.md", "iri-api.md"),
    ("running-jobs/index.md", "running-jobs.md"),
    ("running-jobs/example-job-scripts.md", "example-job-scripts.md"),
    ("polaris/getting-started.md", "polaris-getting-started.md"),
    ("aurora/getting-started-on-aurora.md", "aurora-getting-started.md"),
    ("data-management/filesystem-and-storage/index.md", "file-systems.md"),
    ("account-project-management/allocation-management/allocation-management.md", "allocations.md"),
]

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ok, failed = 0, []
    for src, dst in PAGES:
        url = f"{RAW}/{src}"
        try:
            r = requests.get(url, timeout=30)
            if r.status_code == 200 and r.text.strip():
                (OUT / dst).write_text(r.text, encoding="utf-8")
                ok += 1
                print(f"  ok   {dst}  ({len(r.text)} bytes)")
            else:
                failed.append((src, r.status_code))
                print(f"  FAIL {src}  HTTP {r.status_code}")
        except Exception as exc:  # noqa: BLE001
            failed.append((src, str(exc)))
            print(f"  FAIL {src}  {exc}")

    (OUT / "README.md").write_text(
        "# ALCF docs snapshot\n\n"
        "Auto-generated by `scripts/fetch_docs.py` (nightly CI). Do not edit by "
        "hand — changes are overwritten. Source: "
        "https://github.com/argonne-lcf/user-guides\n",
        encoding="utf-8",
    )
    print(f"\nFetched {ok}/{len(PAGES)} pages; {len(failed)} failed.")
    # Don't fail the whole job if a single page moved; only fail if nothing came.
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
